/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 monkey.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Monkey(props) {
  const { nodes, materials } = useGLTF('/monkey.glb')
  console.log(materials)
  const materiala = materials["Material.001"]
  materiala.color.set("#ffc00")
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Suzanne.geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('/monkey.glb')
